### ISSUE TITLE
Design enhancement docs page

### ISSUE THREAD

**Issue by daannagtegaal** [anchorchat/anchor-ui#181]
- Show where you are on the left menu, make a active list item.
- More vertical spacing between Title, Description, Usage, Examples and Props

**Comment by sjaakluthart** [comment]
Is this for the docs page?

**Comment by daannagtegaal** [comment]
yes

**Comment by IanCStewart** [comment]
do have a clear style u would like to see this in?

**Comment by Ralphvandodewaard** [comment]
https://github.com/anchorchat/anchor-ui/pull/480
