### ISSUE TITLE
Allow for different styles of messages

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#184]
- [x] Create a design
- [x] Implement design

**Comment by daannagtegaal** [comment]
![screen shot 2017-02-14 at 16 56 16](https://cloud.githubusercontent.com/assets/3033357/22936727/ace72bf2-f2d6-11e6-9cdd-3307cf43451b.png)

**Comment by daannagtegaal** [comment]
See sketch file for more info

**Comment by daannagtegaal** [comment]
https://github.com/anchorchat/anchor-ui/issues/184 Same issue
