### ISSUE TITLE
Add more components

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#204]
- [x] Search input
- [x] Pop-over menu
- [x] IconMenu for PopOver
- [x] Menu items
- [x] Tabs
- [x] More lines of data for profile card
- [x] Settings dialog
- [x] Profile sidebar
- [x] Add title to List
- [x] Banners
- [x] Checkbox/ toggle
- [x] Divider
- [x] Radio button
- [x] Select
- [x] Drawer, something like http://www.material-ui.com/#/components/drawer

**Comment by daannagtegaal** [comment]
Image upload design in sketchfile
