### ISSUE TITLE
Add docs pages for missing components

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#220]
- [x] MenuItem
- [x] IconMenu
- [x] Banner
- [x] SearchBox
- [x] WithTheme
- [x] Card
- [x] Checkbox
- [x] Divider
- [x] EmojiMenu
- [x] Menu
- [x] Profile
- [x] RadioButton
- [x] Select
- [x] Tabs
- [x] Switch
- [x] PopOver
- [x] Slider

**Comment by MrBamBam** [comment]
Added all components in the list. PopOver is not visible (no error). Banner is not visible (no error).

Will try to fix as we speak.
