### ISSUE TITLE
Layer issue

### ISSUE THREAD

**Issue by MartijnReeuwijk** [anchorchat/anchor-ui#251]
The menu doesn't go to the proper layer it needs to be
![screen shot 2017-02-28 at 11 19 25](https://cloud.githubusercontent.com/assets/15121010/23403640/50c67fe0-fdb1-11e6-899e-df6e708c359f.png)

**Comment by sjaakluthart** [comment]
https://github.com/anchorchat/anchor-ui/commit/f505f3989f034cc6da81ece1ce23cb35d339e45e
