### ISSUE TITLE
Add submit option for buttons inside forms

### ISSUE THREAD

**Issue by larstadema** [anchorchat/anchor-ui#310]
When using this component, it would be much easier if we can use a submit prop. Instead of creating a onClick action on a form submit. 
Right now the following needs to be done:
```
<form ref={(node) => { this.form = node; }} onSubmit={handleSubmit}>
      <Button onClick={() => this.form.submit()}>
        <I18n text="sign-in" />
      </Button>
</form>
```

Instead of something like this:
```
<form onSubmit={handleSubmit}>
      <Button form={true}>
        <I18n text="sign-in" />
      </Button>
</form>
```

**Comment by larstadema** [comment]
This is also hacky due to required props`<Button onClick={() => {}} style={style.button}>`

**Comment by sjaakluthart** [comment]
I've added custom props to Button #313
