### ISSUE TITLE
maxHeight and number of display items for Select

### ISSUE THREAD

**Issue by larstadema** [anchorchat/anchor-ui#389]
If you have alot of data inside an select box, there is no scrollbar inside it, and the select falls outside the viewport. 

Would be nice if we could specify the maxNumber of items to display and have a scrollbar inside it.

And next to that a check on basis of the bottom of the screen

**Comment by IanCStewart** [comment]
Added a `maxHeight` style to the pop-over. We will have to make a better fix some day.

**Comment by IanCStewart** [comment]
Tried to fix this. It's not gonna be pretty, decided to drop this.
