### ISSUE TITLE
Fix Alert styles

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#409]
<img width="511" alt="55375576-issue-401" src="https://cloud.githubusercontent.com/assets/6596471/25183074/d65b0a2c-2516-11e7-814c-2e820ed91f16.png">

Text should always be on one line if there's enough space

**Comment by daannagtegaal** [comment]
This <img width="537" alt="screen shot 2017-04-20 at 08 53 52" src="https://cloud.githubusercontent.com/assets/3033357/25217521/8de5e6a4-25a7-11e7-86dd-bcc3ab8daa71.png">
 or this?<img width="582" alt="screen shot 2017-04-20 at 08 56 30" src="https://cloud.githubusercontent.com/assets/3033357/25217520/8de3683e-25a7-11e7-928f-d42afd62d340.png">

**Comment by daannagtegaal** [comment]
Change error type alert to  #B63732
