### ISSUE TITLE
Expand docs pages

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#446]
- [x] Add prop tables for CardHeader and CardContent to the `Card` page in docs, See the RadioButton page for examples

- [x] Add examples for components that change style or behaviour based on props, for example: a `disabled` Input, a Message with `compact` styles and a nested List in a ListItem. Check the `props` table for each component to see what the options are.

**Comment by Ralphvandodewaard** [comment]
https://github.com/anchorchat/anchor-ui/pull/452
https://github.com/anchorchat/anchor-ui/pull/459
