### ISSUE TITLE
Add text-overflow to more components. See screens

### ISSUE THREAD

**Issue by larstadema** [anchorchat/anchor-ui#456]
<img width="451" alt="screen shot 2017-05-02 at 12 05 01" src="https://cloud.githubusercontent.com/assets/16486197/25614105/e683d4a0-2f30-11e7-8f0b-f9c486e439b9.png">
<img width="427" alt="screen shot 2017-05-02 at 12 05 52" src="https://cloud.githubusercontent.com/assets/16486197/25614106/e684894a-2f30-11e7-9632-831fe073815a.png">
<img width="414" alt="screen shot 2017-05-02 at 12 06 23" src="https://cloud.githubusercontent.com/assets/16486197/25614107/e684fc36-2f30-11e7-9f73-772a980bad8d.png">
<img width="393" alt="screen shot 2017-05-02 at 12 07 25" src="https://cloud.githubusercontent.com/assets/16486197/25614108/e68733a2-2f30-11e7-973d-a3001aef331a.png">
<img width="396" alt="screen shot 2017-05-02 at 12 08 01" src="https://cloud.githubusercontent.com/assets/16486197/25614109/e687556c-2f30-11e7-8150-fb19ff04c3dd.png">

**Comment by Ralphvandodewaard** [comment]
https://github.com/anchorchat/anchor-ui/pull/480/
