### ISSUE TITLE
ListItems texts need more lineHeight

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#462]
<img width="243" alt="screen shot 2017-05-02 at 15 55 22" src="https://cloud.githubusercontent.com/assets/6596471/25620830/e9f28ff4-2f4f-11e7-81bd-fc811944f61d.png">
<img width="280" alt="screen shot 2017-05-02 at 17 08 54" src="https://cloud.githubusercontent.com/assets/6596471/25624820/e88ddcc6-2f5a-11e7-9715-dc417148ef67.png">
<img width="255" alt="screen shot 2017-05-02 at 17 12 49" src="https://cloud.githubusercontent.com/assets/6596471/25624819/e88dbbd8-2f5a-11e7-9565-ac91f5754bd5.png">
<img width="258" alt="screen shot 2017-05-02 at 17 14 49" src="https://cloud.githubusercontent.com/assets/6596471/25624821/e890191e-2f5a-11e7-92c0-655edb71a9f5.png">

**Comment by larstadema** [comment]
Part of the fix already done, just noticed these small things:

<img width="252" alt="screen shot 2017-05-03 at 14 03 35" src="https://cloud.githubusercontent.com/assets/16486197/25659734/6b203a2c-3009-11e7-9cb0-3ec83b9ea614.png">
<img width="247" alt="screen shot 2017-05-03 at 14 03 43" src="https://cloud.githubusercontent.com/assets/16486197/25659735/6b39c942-3009-11e7-9396-db48dfbd1233.png">
