### ISSUE TITLE
Buttons stuck in hover state

### ISSUE THREAD

**Issue by Ralphvandodewaard** [anchorchat/anchor-ui#474]
Example #1: When in Profile Settings, press the edit icon to change email/password, then press the Cancel button. The edit icon will still be in its hover state.

Example #2: When pressing the Edit icon, the Cancel button will already be in its hover state.

![hoveredit](https://cloud.githubusercontent.com/assets/24306161/25797417/66c9360e-33dd-11e7-8008-6a18e620f29f.png)
![hovercancel](https://cloud.githubusercontent.com/assets/24306161/25797420/697a89b6-33dd-11e7-8bb3-6de533cc6f25.png)

**Comment by IanCStewart** [comment]
Should be in anchor-chat-client not here
