### ISSUE TITLE
withTheme hoc needs a shouldComponentUpdate

### ISSUE THREAD

**Issue by larstadema** [anchorchat/anchor-ui#481]
See the following screenshot:

off the 110ms this call took, it took over 20ms to render a withTheme where there were no changes.

<img width="911" alt="screen shot 2017-05-09 at 13 33 58" src="https://cloud.githubusercontent.com/assets/16486197/25848807/424bbcb8-34bc-11e7-837d-0106fa8ee909.png">

**Comment by sjaakluthart** [comment]
#485

**Comment by peterkuiper** [comment]
I'm missing the after screenshot so we can see if it actually had any effect
