### ISSUE TITLE
Refactor the use of context to be more safe

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#507]
See this [article](https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076)

**Comment by peterkuiper** [comment]
If we can't figure out a nice way to fix this, we may want to leave it as-is for now.

**Comment by sjaakluthart** [comment]
create an extendable class that contains all the new theme logic

so we can do this

```js
class Button extends ThemedComponent
```

**Comment by peterkuiper** [comment]
This way, you can make ThemedComponent such that is has the basic lifecycle methods for subscribing and unbsubscribing to context. This way, if something changes in the React API you probably (hopefully) have less work to fix it :)

**Comment by peterkuiper** [comment]
And, it makes the Anchor-UI components easier to read.

**Comment by sjaakluthart** [comment]
#516
