### ISSUE TITLE
[PopOver] IE 11 streched out menu

### ISSUE THREAD

**Issue by MartijnReeuwijk** [anchorchat/anchor-ui#515]
![screen shot 2017-05-16 at 16 36 00](https://cloud.githubusercontent.com/assets/15121010/26111729/2d9ff460-3a56-11e7-89f8-6701cdd91c21.png)

**Comment by IanCStewart** [comment]
Same problem as #531 can't fix at this moment. Initial rendering is breaking this.

**Comment by IanCStewart** [comment]
can't reproduce
