### ISSUE TITLE
[Loader] Create a loader that can be used inside buttons

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#631]
<img width="121" alt="screen shot 2017-06-02 at 11 01 41" src="https://cloud.githubusercontent.com/assets/6596471/26719206/ea7ef3c6-4783-11e7-810f-8e34d2e47ae3.png">

This looks a little weird

**Comment by sjaakluthart** [comment]
Maybe a circular loader will look better.

See this [page](https://uxplanet.org/practical-guide-to-creating-custom-animated-loading-indicators-55d68d735edc)

**Comment by IanCStewart** [comment]
Redundant
