### ISSUE TITLE
Styles are applied for each item in a loop, should be only for the first

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#64]
![image](https://cloud.githubusercontent.com/assets/6596471/21933389/88fe0db8-d9a5-11e6-8bc3-82e3fdb2ea60.png)

**Comment by sjaakluthart** [comment]
Investigate using this method
https://github.com/cssinjs/jss/blob/master/docs/js-api.md#add-a-rule-to-an-existing-style-sheet

**Comment by IanCStewart** [comment]
Link that is provided above doesn't solve our problem

**Comment by sjaakluthart** [comment]
We should drop style overrides or find a better solution, may be with another library like [Radium](https://github.com/FormidableLabs/radium)

**Comment by sjaakluthart** [comment]
https://github.com/cssinjs/react-jss/issues/69

**Comment by sjaakluthart** [comment]
Resolved by porting to Radium
