### ISSUE TITLE
List items need separation

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#65]
![image](https://cloud.githubusercontent.com/assets/6596471/21933443/bc33ef04-d9a5-11e6-84be-33fed0b062a7.png)

this is unclear

- [x] Design solution
- [ ] Implement solution

**Comment by daannagtegaal** [comment]
![screen shot 2017-01-16 at 10 01 11](https://cloud.githubusercontent.com/assets/3033357/21976569/ca2d3bc2-dbd2-11e6-90f8-6a8027bb48df.png)
Design Solution

**Comment by sjaakluthart** [comment]
#79 
https://github.com/anchorchat/anchor-ui/pull/79
