### ISSUE TITLE
Add new icons for admin dashboard

### ISSUE THREAD

**Issue by daannagtegaal** [anchorchat/anchor-ui#670]
See icons in sketch

**Comment by daannagtegaal** [comment]
<img width="686" alt="screen shot 2017-06-12 at 09 45 03" src="https://user-images.githubusercontent.com/3033357/27023666-d952f2f0-4f53-11e7-8f3c-e2b38c5ed5d5.png">

**Comment by daannagtegaal** [comment]
<img width="637" alt="screen shot 2017-06-12 at 10 13 40" src="https://user-images.githubusercontent.com/3033357/27024667-d58ef0b6-4f57-11e7-983e-8b3c4982117b.png">
Updated icons

**Comment by Ralphvandodewaard** [comment]
https://github.com/anchorchat/anchor-ui/pull/673
