### ISSUE TITLE
Add a divider for older Messages 

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#700]
Something like this

<img width="580" alt="screen shot 2017-06-14 at 10 18 49" src="https://user-images.githubusercontent.com/6596471/27123041-ed831f30-50ec-11e7-96c9-0b97d0e1b72d.png">

**Comment by daannagtegaal** [comment]
<img width="663" alt="screen shot 2017-06-16 at 09 07 38" src="https://user-images.githubusercontent.com/3033357/27215809-48608b7c-5273-11e7-8430-a207a4a89f61.png">
