### ISSUE TITLE
Add option for custom props on components

### ISSUE THREAD

**Issue by larstadema** [anchorchat/anchor-ui#73]
If I want to add custom props to a component we can do it with the following code:

`
    const { children, listRef, ...other } = this.props;
    const { className } = this.state;

    if (listRef) {
      return <ul ref={listRef} {...other} className={className}>{children}</ul>;
    }

    return <ul {...other} className={className}>{children}</ul>;
`

This will add a issue with the sheet prop though.

**Comment by sjaakluthart** [comment]
We should investigate how similar projects handle this, currently I don't see the use of this.
