### ISSUE TITLE
Close on esc

### ISSUE THREAD

**Issue by MrBamBam** [anchorchat/anchor-ui#740]
Current behaviour:
If you open a picture with lightbox you'll be able to navigate away from that image by clicking outside the image or on the exit icon in the top right corner.

Wanted behaviour:
If you open a picture with lightbox you should be able to close the lightbox by pressing the escape key (or maybe even other key bindings as well.).

As it started with the lightbox, we came across more components that are in need of this feature.

**Components in need of this feature**
- [x] Dialog
- [x] EmojiMenu [see this pr](https://github.com/anchorchat/anchor-ui/pull/743/files)
- [x] IconMenu
- [x] Lightbox
- [x] Menu
- [x] Select

**Comment by sjaakluthart** [comment]
#743
