### ISSUE TITLE
[EmojiMenu] justify-content

### ISSUE THREAD

**Issue by MrBamBam** [anchorchat/anchor-ui#769]
![screen shot 2017-06-26 at 16 57 26](https://user-images.githubusercontent.com/10127707/27546039-d7816472-5a91-11e7-8547-c31cc556bc67.png)
![screen shot 2017-06-26 at 16 59 21](https://user-images.githubusercontent.com/10127707/27546040-d7849e44-5a91-11e7-829c-f09ee432658b.png)
![screen shot 2017-06-26 at 16 59 29](https://user-images.githubusercontent.com/10127707/27546041-d785d8ea-5a91-11e7-91b9-b7cbd179b84a.png)

More emojis
![image](https://user-images.githubusercontent.com/10127707/27546067-f114db08-5a91-11e7-8c4f-256249f889f6.png)

![image](https://user-images.githubusercontent.com/10127707/27546076-fa5e04aa-5a91-11e7-8eb0-df9e8d826060.png)

**Comment by daannagtegaal** [comment]
Agree with the last screenshot. MAKE IT GREAT AGAIN @IanCStewart
