### ISSUE TITLE
[popOver] Should make it render at the bottom of the root

### ISSUE THREAD

**Issue by IanCStewart** [anchorchat/anchor-ui#783]
It's causing a lot of z-index problems now..

**Comment by sjaakluthart** [comment]
I've added a (semi) working example in [this commit](https://github.com/anchorchat/anchor-ui/commit/aeef3e2032c22db97c18fbe1f4b9b2ee0fe81851)

The 'portal' works, only when the open button is clicked when open, the portal doesn't close
