### ISSUE TITLE
[Message] Move IconMenu into message

### ISSUE THREAD

**Issue by IanCStewart** [anchorchat/anchor-ui#848]

**Comment by daannagtegaal** [comment]
<img width="455" alt="screen shot 2017-09-25 at 16 45 35" src="https://user-images.githubusercontent.com/3033357/30814630-ff074a9a-a210-11e7-91ac-f09cbd87d4d3.png">
Compact
<img width="484" alt="screen shot 2017-09-25 at 16 45 37" src="https://user-images.githubusercontent.com/3033357/30814631-ff21082c-a210-11e7-97eb-1741390f8ead.png">
Clean
