### ISSUE TITLE
[MessageInput] weird black bar on android 7.1.1

### ISSUE THREAD

**Issue by larstadema** [anchorchat/anchor-ui#856]
<img width="600" alt="screen shot 2017-09-12 at 11 11 46" src="https://user-images.githubusercontent.com/16486197/30317860-b75684d2-97ab-11e7-8cc1-9bcf339dc300.png">

<img width="1906" alt="screen shot 2017-09-12 at 11 12 38" src="https://user-images.githubusercontent.com/16486197/30317864-b9154b0a-97ab-11e7-9860-5a37c0577c3e.png">

**Comment by IanCStewart** [comment]
Can't reproduce
