### ISSUE TITLE
Make sure ref actually works

### ISSUE THREAD

**Issue by IanCStewart** [anchorchat/anchor-ui#890]
Adding a ref prop will refer to the radium wrapper now. This is not what we want.

**Comment by larstadema** [comment]
This is actually not entirely true. Radium is a hoc component that adds methods to the underlying class. You can still access the component you want. For example in the message list, this works:

```
const handleClick = () => this.node.scrollDown();

render() {
  <div>
    <MessageList ref={(node) => { this.node = node; }}/>
    <Button onClick={this.handleClick}>Scroll Down!</Button>
  </div>
}
```

**Comment by larstadema** [comment]
In v5 we refactored this entirely: https://github.com/anchorchat/anchor-ui/pull/961
