### ISSUE TITLE
it doesn't work npm run compile

### ISSUE THREAD

**Issue by ivan-comar** [anchorchat/anchor-ui#925]
when I run this command `"compile": "rm -rf dist && babel -d dist/ src/"`, it doesn't work.
the error is like this.

```> anchor-ui@4.5.0 compile E:\test project\anchor-ui
> rm -rf dist && babel -d dist/ src/

'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anchor-ui@4.5.0 compile: `rm -rf dist && babel -d dist/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anchor-ui@4.5.0 compile script 'rm -rf dist && babel -d dist/ src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the anchor-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist && babel -d dist/ src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs anchor-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls anchor-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ivan\AppData\Roaming\npm-cache\_logs\2017-10-30T16_58_40_460Z-debug.log

please teach me kindly how I can fix this error.
thanks,

**Comment by sjaakluthart** [comment]
Hi @ivan-comar,

I've swapped the `rm -rf` command with the `rimraf` node module. The compile script still works on my system (MacOs). Could you confirm this for me? I don't have a Windows system available.

Please open an issue if any other problems occur. 😄

**Comment by ivan-comar** [comment]
@sjaakluthart 
I use Windows. so you mean I can't run this command on Wins.
if so, how can i handle this error? ;(

**Comment by sjaakluthart** [comment]
I forgot to reference the PR in which I've changed the command. Please check out this pull request https://github.com/anchorchat/anchor-ui/pull/927 and run the compile command

**Comment by ivan-comar** [comment]
ok. it works now.
thanks. @sjaakluthart 👍

**Comment by sjaakluthart** [comment]
Just out of curiosity, what are you working on? 😄

**Comment by ivan-comar** [comment]
well, as i mentioned, I got the error when I run the command `npm run compile`.
but after i replace `rm -rf` with `rimraf`, that command works for me.
so now I can run the project.
I appreciate your help. :)

**Comment by IanCStewart** [comment]
We were just wondering what you are building with our project that you needed to run the `compile` command.

Maybe we will be able to help you out with some stuff 😉

**Comment by ivan-comar** [comment]
@IanCStewart 
thanks for your kindness. but my problems were solved. 😄
