### ISSUE TITLE
import Message from 'anchor-ui/message'

### ISSUE THREAD

**Issue by grinono** [anchorchat/anchor-ui#930]
import Message from 'anchor-ui/message'
provides a ReferenceError: root is not defined in the client.

**Comment by IanCStewart** [comment]
Can you please elaborate a bit more. For example follow our simple ![guideline](https://github.com/anchorchat/anchor-ui/blob/develop/CONTRIBUTING.md#opening-an-issue) to create a bit more context for us.

Very important will be the version you are running. And how/ where u import this.

looking forward to your reply!

**Comment by grinono** [comment]
sure,
process i quite standard, i upgrade some packages to see the result.
new environment:

> node 8.4.0
> meteor 1.6
> react 16.0.0
> react-dom 16.0.0
> anchor-ui 4.5.1

```
yarn add anchor-ui 
import MessageInput from 'anchor-ui/message-input'
```
importing any of the other Anchor components i tested works just fine, 

error now is:

`Cannot find module 'react-dom/lib/HTMLDOMPropertyConfig'`

**Comment by IanCStewart** [comment]
@grinono thanks for the find. Turns out some modules wont work in react 16. After a simple update we will have fixed this 😄
