### ISSUE TITLE
[Menu] content scrolls under header

### ISSUE THREAD

**Issue by sjaakluthart** [anchorchat/anchor-ui#937]
<img width="261" alt="screen shot 2017-11-03 at 20 19 17" src="https://user-images.githubusercontent.com/6596471/32392056-62bcaa44-c0d4-11e7-8a59-e7677dd5b502.png">

When you scroll all the way down, the header also scrolls...

It should either always scroll underneath the header or the header should scroll with the MenuItems

**Comment by larstadema** [comment]
Easy to see on windows:

![45c342597ea152f64bdd6862979c3f95](https://user-images.githubusercontent.com/16486197/32405298-0b331f4e-c163-11e7-963f-3a8ebe008d39.png)
